Fix error : Uncaught TypeError: cb is not a function
Mongoose: 4.2.4
Node: 5.0.0

In some case the method schema.methods.save is called with 2 arguments,
causing the bug. In this case, the first argument always contains this :
 { __noPromise: true }.